language: python
python:
    - "2.7"
install: pip install -r requirements.txt
services: postgresql
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - psql -c 'create database "blogful-test";' -U postgres 

    
script:
    - PYTHONPATH=. python tests/test_filters.py
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py
    - PYTHONPATH=. python tests/test_extensions.py
    # Add any other tests here
    # added -w to see if we can stop password prompt for new ubuntu user
    # added this line to add ubuntu to database
    #     - psql createuser ubuntu  